kind: ZarfPackageConfig
metadata:
  name: dco-core-minimal
  description: "Defensive Cyber Ops (DCO) Suite Core -- but smaller"
  # Big Bang / Iron Bank are only amd64
  architecture: amd64

constants:
  - name: GIT_REF
    description: "Provide the BRANCH (refs/heads/BRANCH) or TAG (refs/tags/TAG) ref to identify the git reference to deploy"
    value: "###ZARF_PKG_TMPL_GIT_REF###"

variables:
  # Prompt user for the domain override
  - name: DOMAIN
    default: "vp.bigbang.dev"
    prompt: false

  - name: KIBANA_COUNT
    default: "0"
    prompt: false

  - name: ES_MASTER_COUNT
    default: "1"
    prompt: false

  - name: ES_DATA_COUNT
    default: "1"
    prompt: false

components:
  - name: flux
    required: true
    manifests:
      - name: flux-installer
        # This will be built on the package create side and deployed as a regular manifest on package deploy
        kustomizations:
          - https://repo1.dso.mil/platform-one/big-bang/bigbang.git//base/flux?ref=1.57.0
    images:
      - registry1.dso.mil/ironbank/fluxcd/helm-controller:v0.30.0
      - registry1.dso.mil/ironbank/fluxcd/kustomize-controller:v0.34.0
      - registry1.dso.mil/ironbank/fluxcd/notification-controller:v0.32.1
      - registry1.dso.mil/ironbank/fluxcd/source-controller:v0.35.2

  - name: minimal-big-bang
    description: "Git repositories and OCI images used by Big Bang Core"
    required: true
    repos:
      # Big Bang
      - https://repo1.dso.mil/big-bang/bigbang.git@1.57.0
      # Istio
      - https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-controlplane.git@1.17.1-bb.0
      - https://repo1.dso.mil/platform-one/big-bang/apps/core/istio-operator.git@1.17.1-bb.0
      # Logging
      - https://repo1.dso.mil/platform-one/big-bang/apps/core/elasticsearch-kibana.git@1.1.0-bb.1
      - https://repo1.dso.mil/platform-one/big-bang/apps/core/eck-operator.git@2.6.1-bb.0

    images:
      # Big Bang
      - "registry1.dso.mil/ironbank/big-bang/base:2.0.0"

      # Istio
      - "registry1.dso.mil/ironbank/opensource/istio/install-cni:1.17.1"
      - "registry1.dso.mil/ironbank/opensource/istio/operator:1.17.1"
      - "registry1.dso.mil/ironbank/opensource/istio/pilot:1.17.1"
      - "registry1.dso.mil/ironbank/opensource/istio/proxyv2:1.17.1"

      - "registry1.dso.mil/ironbank/tetrate/istio/operator:1.16.1-tetratefips-v1"
      - "registry1.dso.mil/ironbank/tetrate/istio/proxyv2:1.16.1-tetratefips-v1"
      - "registry1.dso.mil/ironbank/tetrate/istio/pilot:1.16.1-tetratefips-v1"

      # Logging
      - "registry1.dso.mil/ironbank/elastic/elasticsearch/elasticsearch:8.6.0"
      - "registry1.dso.mil/ironbank/elastic/eck-operator/eck-operator:2.6.1"

      # NOT DISCOVERED BY `zarf prepare` -- must be updated manually
      - "registry1.dso.mil/ironbank/opensource/bitnami/elasticsearch-exporter:1.5.0-debian-11-r17"

    manifests:
      - name: tiny-(big)-bang-config
        kustomizations:
          - "."

  - name: setup
    description: "Required setup for the Zarf CDO package"
    required: true
    repos:
      - https://github.com/naps-dev/dco-core.git
    manifests:
      - name: setup
        files:
          - ../../manifests/setup.yaml

  - name: dataplane-ek
    description: "EK Chart Deployment for the DataPlane"
    required: true
    manifests:
      - name: dataplane-ek
        files:
          - ../../manifests/dataplane-ek.yaml
