###
# Use this config to turn off (or scale down) BB features configured in the standard deployment (`kustomizations/bigbang`)
###

clusterAuditor:
  enabled: false
gatekeeper:
  enabled: false
logging:
  enabled: false
monitoring:
  enabled: false
twistlock:
  enabled: false
fluentbit:
  enabled: false
jaeger:
  enabled: false
kibana:
  enabled: false
kyverno:
  enabled: false
kyvernopolicies:
  enabled: false
neuvector:
  enabled: false