name: Build Arkime Image and Zarf Package
run-name: ${{github.actor}} is building the Arkime image and Zarf package
on:
  push:
    paths:
      - 'arkime/**'
    branches-ignore: [main]
    tags-ignore: ["v**"]
#  pull_request:
#    paths:
#      - 'arkime/**'
#    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  package-create:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      REF_NAME: "main"
      REF_TYPE: "branch"
      ZARF_PACKAGE: zarf-package-arkime-amd64.tar.zst
      IMAGE_TAG: "v4.2.0"
      COMPONENT: "arkime"
