name: Build Arkime Image and Zarf Package
run-name: ${{github.actor}} is building the Arkime image and Zarf package
on:
#  push:
#    paths:
#      - 'arkime/**'
#    branches-ignore: [main]
#    tags-ignore: ["v**"]
  pull_request:
    paths:
      - 'arkime/**'
#    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  package-create:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      REF_NAME: "${{ github.head_ref || github.ref_name }}"
      REF_TYPE: "${{ github.ref_type }}"
      ZARF_PACKAGE: zarf-package-arkime-amd64.tar.zst
      COMPONENT: "arkime"
