name: Build and Deploy Mockingbird Zarf Package
run-name: ${{github.actor}} is building the Mockingbird Zarf package
on:
  push:
    paths:
      - 'mockingbird/**'
      - 'test/mockingbird_package_test.go'
      - '.github/workflows/mockingbird.yaml'
      - '.github/workflows/package.yaml'
    branches-ignore: [main]
    tags-ignore: ["v**"]

permissions:
  id-token: write
  contents: read

jobs:
  package-create:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      REF_NAME: "main"
      REF_TYPE: "branch"
      ZARF_PACKAGE: zarf-package-mockingbird-amd64.tar.zst
      IMAGE_TAG: "main"
      COMPONENT: "mockingbird"
