name: Build and Deploy Polarity Zarf Package
run-name: ${{github.actor}} is building the Polarity Zarf package
on:
  push:
    paths:
      - 'polarity/**'
      - 'test/polarity_package_test.go'
      - '.github/workflows/polarity.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  prepare-polarity:
    runs-on: [self-hosted, onprem]

    steps:
      - name: Set up license file
        run:
          echo "${{ secrets.POLARITY_LICENSE }}" >> /tmp/polarity.lic

  package-create:
    needs: [prepare-polarity]
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      REF_NAME: "main"
      REF_TYPE: "branch"
      ZARF_PACKAGE: zarf-package-polarity-amd64.tar.zst
      COMPONENT: "polarity"

  cleanup-xsoar:
    needs: [package-create]
    if: always()
    runs-on: [self-hosted, onprem]

    steps:
      - name: Remove license file
        run:
          rm -f /tmp/polarity.lic
