name: Build and Deploy Polarity Zarf Package
run-name: ${{github.actor}} is building the Polarity Zarf package
on:
  push:
    paths:
      - 'polarity/**'
      - '.github/workflows/polarity.yaml'
    branches-ignore: [main]
    tags-ignore: ["v**"]

permissions:
  id-token: write
  contents: read

jobs:
  package-create:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      REF_NAME: "main"
      REF_TYPE: "branch"
      ZARF_PACKAGE: zarf-package-polarity-amd64.tar.zst
      COMPONENT: "polarity"
