name: Build and Deploy Suricata Zarf Package
run-name: ${{github.actor}} is building the Suricata package
on:
  push:
    paths:
      - 'suricata/**'
      - '.github/workflows/suricata.yaml'
      - '.github/workflows/package.yaml'
    branches-ignore: [main]
    tags-ignore: ["v**"]

permissions:
  id-token: write
  contents: read

jobs:
  package-create:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      REF_NAME: "main"
      REF_TYPE: "branch"
      ZARF_PACKAGE: zarf-package-suricata-amd64.tar.zst
      COMPONENT: "suricata"
