name: Build Component Image and Zarf Package
run-name: ${{github.actor}} is building the Suricata image and Zarf package
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - './suricata/**'

permissions:
  id-token: write
  contents: read

jobs:
  package-create:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      REF_NAME: "${{ github.head_ref || github.ref_name }}"
      REF_TYPE: "${{ github.ref_type }}"
      ZARF_PACKAGE: zarf-package-suricata-amd64.tar.zst
      COMPONENT: "suricata"
