name: Build and Deploy XSoar Zarf Package
run-name: ${{github.actor}} is building the XSoar Zarf package
on:
  push:
    paths:
      - 'xsoar/**'
      - 'test/xsoar_package_test.go'
      - '.github/workflows/xsoar.yaml'
      - '.github/workflows/package.yaml'
    branches-ignore: [main]
    tags-ignore: ["v**"]

permissions:
  id-token: write
  contents: read

jobs:
  package-create:
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      REF_NAME: "main"
      REF_TYPE: "branch"
      ZARF_PACKAGE: zarf-package-xsoar-amd64.tar.zst
      IMAGE_TAG: "main"
      COMPONENT: "xsoar"
