name: Build and Deploy XSoar Zarf Package
run-name: ${{github.actor}} is building the XSoar Zarf package
on:
  push:
    paths:
      - 'xsoar/**'
      - 'test/xsoar_package_test.go'
      - '.github/workflows/xsoar.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  prepare-xsoar:
    runs-on: [self-hosted, onprem]

    steps:
      - name: Login to XSOAR registry
        run: |
          zarf tools registry login \
            -u "${{secrets.XSOAR_USERNAME}}" \
            -p "${{secrets.XSOAR_PASSWORD}}" \
            "xsoar-registry.pan.dev"

      - name: Set up license file
        run:
          echo "${{ secrets.XSOAR_LICENSE }}" >> /tmp/demisto.lic

  package-create:
    needs: [prepare-xsoar]
    uses: ./.github/workflows/package.yaml
    secrets: inherit
    with:
      REF_NAME: "main"
      REF_TYPE: "branch"
      ZARF_PACKAGE: zarf-package-xsoar-amd64.tar.zst
      IMAGE_TAG: "main"
      COMPONENT: "xsoar"

  cleanup-xsoar:
    needs: [package-create]
    if: always()
    runs-on: [self-hosted, onprem]

    steps:
      - name: Remove license file
        run:
          rm -f /tmp/demisto.lic
